@Library("jenlib") _

wafDefaultPipeline(projects: ["pyhid"],
                   container: [app: "visionary-dls"],
                   notificationChannel: "#softies",
                   warningsIgnorePattern: ".*",
                   enableClangFormat: false)
